language: cpp

compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq autopoint libfuse-dev libboost-serialization-dev
   librlog-dev

script:
 - autoreconf -if
 - ./configure
 - make
 - ./encfs/test
