language: cpp

sudo: false

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - coverity_scan
    - travis

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "KuAAwjiIqkk4vqSX/M3ZZIvQs6edm+tV8IADiklTUYZIFyxu8FgZ6RbDdMD2sef5bNZA1OZhlcbeRtiKff5CfMtvzc607Lg3NUkpi+ShMynWgqS/e0uCMf9ogEJlUiZMxf4juBi7v6DyMl/WV6pAdJmdfHtzcj8GF2mgTfQjkO8="

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make && ./checkops ; fi

addons:
  coverity_scan:
    project:
      name: "vgough/encfs"
      description: "Build submitted via Travis CI"
    notification_email: vgough@pobox.com
    build_command_prepend: "cd build && make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang
      - cmake
      - libfuse-dev
      - libgettextpo-dev

